use super::transitions::{ci_validation_fresh, pred_claim_audit_clean, pred_conc_obligations_ready, pred_idempotent_dispatch_replay_safe, pred_lean_always_true, pred_lean_contract_recorded, pred_lean_net_negative, pred_lean_one_task_in_flight, pred_mutables_all_resolved, pred_mutables_all_typed, pred_no_admit_deferral_markers, pred_pool_floor_met, pred_no_graphical_symbols_in_diff, pred_no_hedge_language_in_diff, pred_no_secrets_in_diff, pred_no_synthetic_test_files, pred_no_unchecked_panics_in_diff, pred_prd_all_closed, pred_remote_hook_refused, pred_res_obligations_ready, pred_sec_obligations_ready, pred_state_obligations_ready, pred_submodules_clean, pred_worktree_clean, residual_scan_fired, split_context_swept};

pub type PredicateFn = fn() -> bool;

pub const PREDICATE_REGISTRY: &[(&str, &str, PredicateFn)] = &[
    ("residual-scan-fired", "true while .gm/residual-check-fired parses as `<session_id>:<fired_at_ms>` and that session_id is the current one (or, with no session id stamped, the stamp is within policy.longgap_threshold_ms). It is NOT invalidated by unrelated dispatches -- only by a PRD/mutable write (prd-add, mutable-add, prd-defer, mutable-defer), which rewrites the marker to `invalidated:<verb>`. A prd-add that reports already_identical does not invalidate. The denial message names which case fired.", residual_scan_fired),
    ("prd-all-closed", "true when .gm/prd.yml has zero rows with an open status (pending/in-progress, not completed)", pred_prd_all_closed),
    ("mutables-all-resolved", "true when .gm/mutables.yml has zero rows still in unknown/pending status", pred_mutables_all_resolved),
    ("mutables-all-typed", "true when every PENDING row in .gm/mutables.yml tagged with a PROVE-kind obligation_kind (precondition/invariant/postcondition/resource-bound/type-shape) has a valid kind AND every id in its depends_on is already resolved. Resolved rows and rows tagged with a different phase's kind never block this gate. The gate message names the specific blocking row and reason.", pred_mutables_all_typed),
    ("state-obligations-ready", "true when every PENDING row tagged with a STATE-kind obligation_kind (totality/ownership/replay/effect-boundary) is validly typed and dependency-resolved. Same DAG mechanics as mutables-all-typed, scoped to STATE's own obligation kinds.", pred_state_obligations_ready),
    ("conc-obligations-ready", "true when every PENDING row tagged with a CONC-kind obligation_kind (happens-before/disjointness/contention) is validly typed and dependency-resolved.", pred_conc_obligations_ready),
    ("sec-obligations-ready", "true when every PENDING row tagged with a SEC-kind obligation_kind (secrets/injection/identity-authority/message-timing) is validly typed and dependency-resolved.", pred_sec_obligations_ready),
    ("res-obligations-ready", "true when every PENDING row tagged with a RES-kind obligation_kind (exception-model/partial-failure/degradation/crucible) is validly typed and dependency-resolved.", pred_res_obligations_ready),
    ("worktree-clean", "true when `git status --porcelain` is empty; non-git projects have no worktree to commit", pred_worktree_clean),
    ("ci-validated-fresh", "true for a non-git project, otherwise when .gm/exec-spool/.ci-validated exists and its head_sha matches the current `git rev-parse HEAD` -- a witnessed-green CI run for the exact pushed commit", ci_validation_fresh),
    ("claim-audit-clean", "true for a non-git project, otherwise when the claim audit finds no unwitnessed completion claims -- see orchestrator::claim_audit", pred_claim_audit_clean),
    ("submodules-clean", "true when no submodule has drifted from its recorded commit -- see orchestrator::submodule_drift", pred_submodules_clean),
    ("no-synthetic-test-files", "true when the working diff introduces no standing test file (*.test.*, *.spec.*, or a test/tests/__tests__ directory). VERIFY doctrine forbids them: verification is a live exec_js witness against real code, never a suite asserting against mocks. Emits deviation.synthetic-test-file naming the offending paths when it fails.", pred_no_synthetic_test_files),
    ("remote-hook-refused", "always false. Substituted by fsm::graph() for a gate whose ONLY condition was a hook supplied by the compiled-default tier, which never legitimately carries one: the author's condition is genuinely not being evaluated and the edge it guards must not be waved through. Local and source-repo tier hooks both execute normally and never hit this substitution. Vendor the graph (and its hook) into .gm/instructions/fsm/graph.json, or configure source.json, to restore the gate.", pred_remote_hook_refused),
    ("no-admit-deferral-markers", "true when new lines in source files (*.rs/.js/.ts/.py/.go/...) in the working diff introduce no colon-form admit marker (TODO:/FIXME:/XXX:/HACK:), no todo!()/unimplemented!() placeholder macro, and no 'not (yet) implemented' phrase. Source-scoped so the rule's own registry and prose describing it do not self-trip; prose-level deferral is covered by no-hedge-language-in-diff. A marker stands in for a complete proof. Emits deviation.admit-deferral-marker naming the offending lines when it fails.", pred_no_admit_deferral_markers),
    ("no-secrets-in-diff", "true when the working diff introduces no line matching a high-confidence secret shape (AWS-style access key id, a private-key PEM header, a bearer/API token assigned to a literal string of plausible entropy, a database URL with an inline password). Heuristic and diff-scoped, not a substitute for a dedicated secret scanner -- catches the common accidental-commit shape. Emits deviation.secret-in-diff naming the offending lines (redacted) when it fails.", pred_no_secrets_in_diff),
    ("no-unchecked-panics-in-diff", "true when new Rust/JS/TS lines in the working diff introduce no bare unwrap()/expect()/panic!() outside a test-only-configured Rust module or *.test.* path, and no JS/TS line that throws without a paired catch reachable in the same function body scope (best-effort, brace-balance heuristic). Exception model requires every raised error handled or explicitly propagated, never left to crash the process uncaught. Emits deviation.unchecked-panic naming the offending lines when it fails.", pred_no_unchecked_panics_in_diff),
    ("no-hedge-language-in-diff", "true when prose files (*.md) touched in the working diff introduce no hedge/deferral phrase ('todo later', 'in a future session', 'for now we', 'as a stopgap', 'good enough for now', 'left as an exercise', 'out of scope for this'). Decisive commitment forbids shipping a hedge in place of a decision. Emits deviation.hedge-language naming the offending lines when it fails.", pred_no_hedge_language_in_diff),
    ("split-context-swept", "true when the working diff touches at most one file, OR .gm/exec-spool/.split-context-swept exists with a head_sha matching the current `git rev-parse HEAD` -- a witnessed independent-Agent adversarial review for the exact pushed multi-file commit. A self-reviewed multi-file diff has not been adversarially swept.", split_context_swept),
    ("no-graphical-symbols-in-diff", "true when new lines in the working diff introduce no decorative non-ASCII glyph (arrows, box-drawing, stars, bullets, checks/crosses, emoji) outside a binary/frozen-changelog/icon-font exemption path. Matches AGENTS.md's own no-graphical-symbols discipline as a real gate instead of an on-sight-only rule. Emits deviation.graphical-symbol naming the offending lines when it fails.", pred_no_graphical_symbols_in_diff),
    ("idempotent-dispatch-replay-safe", "true when the most recent N dispatch audit-tuples (id, hash, ts) for the current stop window contain no exact-duplicate (id, hash) pair recorded as two DIFFERENT outcomes -- a same-input dispatch replayed must reach the same result (f-compose-f-equals-f), never a second, different mutation applied on top of the first. Emits deviation.non-idempotent-replay naming the conflicting tuples when it fails.", pred_idempotent_dispatch_replay_safe),
    ("lean-one-task-in-flight", "BLOCKING. True when at most one row of .gm/prd.yml has an in-progress status.", pred_lean_one_task_in_flight),
    ("lean-contract-only-description", "ADVISORY. Code cannot tell whether prose restates the code, so the predicate always returns true and never refuses.", pred_lean_always_true),
    ("lean-hop-witness-receipt", "ADVISORY. A hop's transition must name an executed witness (a command, crawl result or codesearch output) in its walk note. No receipt writer exists yet, so the predicate always returns true; it becomes BLOCKING once a writer records each hop's witness.", pred_lean_always_true),
    ("lean-verifier-independent", "ADVISORY. Code cannot observe what a verifier agent read, so the predicate always returns true and never refuses.", pred_lean_always_true),
    ("lean-net-negative", "BLOCKING. True when the working tree diff against HEAD has added lines less than or equal to removed lines. A growth reason is not read, so a growing change is refused.", pred_lean_net_negative),
    ("pool-floor-met", "BLOCKING. True when pool_slots::slot_state reports action other than launch: no open PRD row (action none), or open rows with zero free slots (action hold). With no recorded spawn ceiling, free is null and the gate stays false until pool-observe records a spawn refusal. The denial names open_rows, live, free and action.", pred_pool_floor_met),
    ("lean-contract-recorded", "BLOCKING. True when every .gm/prd.yml row is closed and the worktree is clean. The reason text in the commit message is not read.", pred_lean_contract_recorded),
];

pub fn generated_predicates_md() -> String {
    let mut out = String::from(
        "# Compiled FSM gate predicates\n\nGENERATED from rs-plugkit's crates/plugkit-core/src/orchestrator/predicate_registry.rs's PREDICATE_REGISTRY -- do not hand-edit. Regenerate by dispatching the `predicates-md` verb (body ignored) against a project with the current plugkit.wasm loaded and replacing this file's body with the returned predicates_md field; a CI check in rs-plugkit diffs a fresh regeneration against its own committed copy and fails on drift, and this file must be kept in sync with that copy by the same discipline.\n\nReference for `gates.predicate` in .gm/instructions/fsm/graph.json's `gates` array -- a predicate name here is the ONLY thing a graph's gates array can reference directly; a genuinely new condition needs a jit hook instead (see hooks/example.js) or a Rust change to add a new compiled predicate.\n\n",
    );
    for (name, desc, _) in PREDICATE_REGISTRY {
        out.push_str(&format!("- `{name}` -- {desc}\n"));
    }
    out
}
