pub const PREDICATE_REGISTRY: &[(&str, &str)] = &[
    ("residual-scan-fired", "true once `residual-scan` has been dispatched in this stop window (the .gm/residual-check-fired marker is present AND non-empty -- it is invalidated by truncation)"),
    ("prd-all-closed", "true when .gm/prd.yml has zero rows with an open status (pending/in-progress, not completed)"),
    ("mutables-all-resolved", "true when .gm/mutables.yml has zero rows still in unknown/pending status"),
    ("mutables-all-typed", "true when every PENDING row in .gm/mutables.yml tagged with a PROVE-kind obligation_kind (precondition/invariant/postcondition/resource-bound/type-shape) has a valid kind AND every id in its depends_on is already resolved. Resolved rows and rows tagged with a different phase's kind never block this gate. The gate message names the specific blocking row and reason."),
    ("state-obligations-ready", "true when every PENDING row tagged with a STATE-kind obligation_kind (totality/ownership/replay/effect-boundary) is validly typed and dependency-resolved. Same DAG mechanics as mutables-all-typed, scoped to STATE's own obligation kinds."),
    ("conc-obligations-ready", "true when every PENDING row tagged with a CONC-kind obligation_kind (happens-before/disjointness/contention) is validly typed and dependency-resolved."),
    ("sec-obligations-ready", "true when every PENDING row tagged with a SEC-kind obligation_kind (secrets/injection/identity-authority/message-timing) is validly typed and dependency-resolved."),
    ("res-obligations-ready", "true when every PENDING row tagged with a RES-kind obligation_kind (exception-model/partial-failure/degradation/crucible) is validly typed and dependency-resolved."),
    ("worktree-clean", "true when `git status --porcelain` is empty -- no uncommitted/unpushed delta"),
    ("ci-validated-fresh", "true when .gm/exec-spool/.ci-validated exists and its head_sha matches the current `git rev-parse HEAD` -- a witnessed-green CI run for the exact pushed commit"),
    ("browser-witness-coverage", "true when every client-side file edited this session (per .gm/exec-spool/.turn-browser-edits.json) has a matching entry in .gm/exec-spool/.turn-browser-witnessed with the same content hash"),
    ("app-loads-witnessed", "true when this project has no .gm/browser-config.json (no declared browser entrypoint, nothing to check), OR the most recent `browser` dispatch this stop window recorded a healthy app-loads witness (ok:true, zero pageErrors, zero console error-level lines) in .gm/exec-spool/.app-loads-witnessed.json. Unlike browser-witness-coverage, this check is unconditional -- it does not read .turn-browser-edits.json and is never vacuously satisfied by an empty edit list, so a zero-edit confirmation/audit turn claiming the app is healthy still must dispatch `browser` this turn to prove it."),
    ("claim-audit-clean", "true when the claim audit finds no unwitnessed completion claims -- see orchestrator::claim_audit"),
    ("submodules-clean", "true when no submodule has drifted from its recorded commit -- see orchestrator::submodule_drift"),
    ("no-synthetic-test-files", "true when the working diff introduces no standing test file (*.test.*, *.spec.*, or a test/tests/__tests__ directory). VERIFY doctrine forbids them: verification is a live exec_js/browser witness against real code, never a suite asserting against mocks. Emits deviation.synthetic-test-file naming the offending paths when it fails."),
    ("remote-hook-refused", "always false. Substituted by fsm::graph() for a gate whose ONLY condition was a hook supplied by the compiled-default tier, which never legitimately carries one: the author's condition is genuinely not being evaluated and the edge it guards must not be waved through. Local and source-repo tier hooks both execute normally and never hit this substitution. Vendor the graph (and its hook) into .gm/instructions/fsm/graph.json, or configure source.json, to restore the gate."),
    ("no-admit-deferral-markers", "true when new lines in source files (*.rs/.js/.ts/.py/.go/...) in the working diff introduce no colon-form admit marker (TODO:/FIXME:/XXX:/HACK:), no todo!()/unimplemented!() placeholder macro, and no 'not (yet) implemented' phrase. Source-scoped so the rule's own registry and prose describing it do not self-trip; prose-level deferral is covered by no-hedge-language-in-diff. A marker stands in for a complete proof. Emits deviation.admit-deferral-marker naming the offending lines when it fails."),
    ("no-secrets-in-diff", "true when the working diff introduces no line matching a high-confidence secret shape (AWS-style access key id, a private-key PEM header, a bearer/API token assigned to a literal string of plausible entropy, a database URL with an inline password). Heuristic and diff-scoped, not a substitute for a dedicated secret scanner -- catches the common accidental-commit shape. Emits deviation.secret-in-diff naming the offending lines (redacted) when it fails."),
    ("no-unchecked-panics-in-diff", "true when new Rust/JS/TS lines in the working diff introduce no bare unwrap()/expect()/panic!() outside a test-only-configured Rust module or *.test.* path, and no JS/TS line that throws without a paired catch reachable in the same function body scope (best-effort, brace-balance heuristic). Exception model requires every raised error handled or explicitly propagated, never left to crash the process uncaught. Emits deviation.unchecked-panic naming the offending lines when it fails."),
    ("no-hedge-language-in-diff", "true when prose files (*.md) touched in the working diff introduce no hedge/deferral phrase ('todo later', 'in a future session', 'for now we', 'as a stopgap', 'good enough for now', 'left as an exercise', 'out of scope for this'). Decisive commitment forbids shipping a hedge in place of a decision. Emits deviation.hedge-language naming the offending lines when it fails."),
    ("split-context-swept", "true when the working diff touches at most one file, OR .gm/exec-spool/.split-context-swept exists with a head_sha matching the current `git rev-parse HEAD` -- a witnessed independent-Agent adversarial review for the exact pushed multi-file commit. A self-reviewed multi-file diff has not been adversarially swept."),
    ("no-graphical-symbols-in-diff", "true when new lines in the working diff introduce no decorative non-ASCII glyph (arrows, box-drawing, stars, bullets, checks/crosses, emoji) outside a binary/frozen-changelog/icon-font exemption path. Matches AGENTS.md's own no-graphical-symbols discipline as a real gate instead of an on-sight-only rule. Emits deviation.graphical-symbol naming the offending lines when it fails."),
    ("idempotent-dispatch-replay-safe", "true when the most recent N dispatch audit-tuples (id, hash, ts) for the current stop window contain no exact-duplicate (id, hash) pair recorded as two DIFFERENT outcomes -- a same-input dispatch replayed must reach the same result (f-compose-f-equals-f), never a second, different mutation applied on top of the first. Emits deviation.non-idempotent-replay naming the conflicting tuples when it fails."),
];

pub fn generated_predicates_md() -> String {
    let mut out = String::from(
        "# Compiled FSM gate predicates\n\nGENERATED from rs-plugkit's crates/plugkit-core/src/orchestrator/predicate_registry.rs's PREDICATE_REGISTRY -- do not hand-edit. Regenerate by dispatching the `predicates-md` verb (body ignored) against a project with the current plugkit.wasm loaded and replacing this file's body with the returned predicates_md field; a CI check in rs-plugkit diffs a fresh regeneration against its own committed copy and fails on drift, and this file must be kept in sync with that copy by the same discipline.\n\nReference for `gates.predicate` in .gm/instructions/fsm/graph.json's `gates` array -- a predicate name here is the ONLY thing a graph's gates array can reference directly; a genuinely new condition needs a jit hook instead (see hooks/example.js) or a Rust change to add a new compiled predicate.\n\n",
    );
    for (name, desc) in PREDICATE_REGISTRY {
        out.push_str(&format!("- `{name}` -- {desc}\n"));
    }
    out
}
